# Generated by Django 5.1.9 on 2025-05-16 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor')], default='student', max_length=20, verbose_name='Role')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/photos/%Y/%m/%d/', verbose_name='Photo')),
                ('bio', models.TextField(blank=True, verbose_name='Biography')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('twitter', models.CharField(blank=True, max_length=100, verbose_name='Twitter')),
                ('facebook', models.CharField(blank=True, max_length=100, verbose_name='Facebook')),
                ('instagram', models.CharField(blank=True, max_length=100, verbose_name='Instagram')),
                ('linkedin', models.CharField(blank=True, max_length=100, verbose_name='LinkedIn')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email notifications')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
