services:
  docs:
    image: educacion_financiera_local_docs
    container_name: educacion_financiera_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./educacion_financiera:/app/educacion_financiera:z
    ports:
      - '9000:9000'
    command: /start-docs
